### ISSUE TITLE
Turn it into a main screen plugin

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-tool#36]
Move the tool from the bottom panel to the right dock.
With this change we can use the default editor output to log errors and info's and the output is always in view.

![image](https://user-images.githubusercontent.com/41547570/224010779-1caf2952-dce3-46b3-bb4a-72247af7feaa.png)

**Comment by Qubus0** [comment]
we could also turn it into a main screen plugin? it would be almost identical to how it is now, just moved up into the main scene. 
* Pro: looks the same, console can be open at the same time, lots of space, json editor is placed be where a code editor would be expected, no double dock tabs
* Con: can't have any scenes or scripts open at the same time, maybe too much space?

we could merge the "export" tab with the manifest tab to make better use of space, since they are also used in tandem. less annoying tab switching

https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_main_screen_plugins.html

![screenshot of demo main screen plugin](https://github.com/godotengine/godot-demo-projects/raw/master/plugins/screenshots/main_screen_plugin.png)
